fp/urls.py
from django.conf.urls import url

from fp import views

urlpatterns = [
    url(r'first', views.first, name='first'),
    url(r'second', views.second, name='second'),
    url(r'third', views.third, name='third'),
    url(r'first_fn', views.first_fn, name='first_fn'),
    url(r'second_fn', views.second_fn, name='second_fn'),
    url(r'third_fn', views.third_fn, name='third_fn'),
]

info/urls.py
from django.conf.urls import url

from info import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'signup', views.signup, name='signup'),
    url(r'login', views.login_user, name='login'),
    url(r'logout', views.logout_user, name='logout'),
    #url(r'activate', views.activate_user, name='activate_user'),
    #url(r'assignment', views.user_assignment, name='user_assignment'),
    url(r'webservice/infoscore', views.info_score_webservice, name='infoscorewebservice'),
    #url(r'comment/score', views.score_comment, name='scorecomment'),
    #url(r'comment/review', views.review_comment, name='reviewcomment'),
    #url(r'webservice', views.web_service, name='webservice'),
    url(r'main', views.main, name='main'),
]

score/urls.py
from django.conf.urls import url

from score import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'signup', views.signup, name='signup'),
    url(r'login', views.login_user, name='login'),
    url(r'logout', views.logout_user, name='logout'),
    url(r'activate', views.activate_user, name='activate_user'),
    url(r'assignment', views.user_assignment, name='user_assignment'),
    url(r'webservice/score', views.score_webservice, name='scorewebservice'),
    url(r'comment/score', views.score_comment, name='scorecomment'),
    url(r'comment/review', views.review_comment, name='reviewcomment'),
    url(r'webservice/review', views.review_webservice, name='reviewwebservice'),
    url(r'webservice/complete', views.complete_webservice, name='completewebservice'),
    url(r'webservice', views.web_service, name='webservice'),
    url(r'main', views.main, name='main'),
]

score_site/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from score_site import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^score/', include('score.urls', namespace="score")),
    url(r'^rate/', include('rate.urls', namespace="rate")),
    url(r'^info/', include('info.urls', namespace="info")),
    url(r'^fp/', include('fp.urls', namespace="fp")),
    #url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += staticfiles_urlpatterns()

info/models.py
from __future__ import unicode_literals

from django.db import models

class MaxMin(models.Model):
    id = models.IntegerField(default=0, primary_key=True)
    name = models.CharField(max_length=50, null=False)
    min = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    mean = models.FloatField(default=0.0)
    stdev = models.FloatField(default=0.0)

info/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from score.models import *
from info.models import *

def index(request):
    """ Index view shows login page.
    :param request: GET request.
    :return response: login page.
    """
    next = request.GET.get('next', 'main')
    return render(request, 'info/login.html', dict(next=next))


@csrf_protect
def login_user(request):
    """ Authenticate a user from login page and create a session, then goes to 'next' page.
    :param request: POST request
    :return response: 'next' page
    """
    if request.method == 'GET':
        raise Http404

    username = request.POST.get('username')
    password = request.POST.get('password')
    next = request.POST.get('next', 'main')

    response_dict = dict()
    user = authenticate(username=username, password=password)

    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(next)
        else:
            response_dict['login_error'] = "Account is not active!"
    else:
        response_dict['login_error'] = "Wrong user or password!"

    response_dict['username'] = username
    return render(request, 'info/login.html', response_dict)


def logout_user(request):
    """ Logout user from the application.
    :param request: GET request.
    :return response: login page.
    """
    logout(request)
    return render(request, 'info/login.html', dict())


@login_required(login_url='/score_site/info')
def main(request):
    """ Web Services view displays all web services assigned to the user.
    :param request: GET request.
    :return response: web services page.
    """
    username = request.user.username
    uwss = UserWebService.objects.filter(user_username=username)
    ws_ids = []
    uws_dict = dict()
    for uws in uwss:
        ws_ids.append(uws.ws_id)
        uws_dict[uws.ws_id] = uws
    apis = WebService.objects.filter(id__in=ws_ids)

    for api in apis:
        api.info_score = -1
        if uws_dict[api.id].status >= 200:
            api.info_score = uws_dict[api.id].info_score

    infos = MaxMin.objects.all()
    return render(request, 'info/main.html', dict(apis=apis, infos=infos))

def info_score_webservice(request):
    username = request.user.username
    ws_id = request.POST.get('ws_id')
    score = request.POST.get('score')
    print ws_id, score
    status = 200
    try:
        user_webservice = UserWebService.objects.get(user_username=username, ws_id=ws_id)
        user_webservice.info_score = score
        user_webservice.status = 200
        user_webservice.save()
    except Exception:
        status = 500
    return JsonResponse({'status': status})

info/templates/info/activate.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Score Web Services</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'score/js/jquery-1.12.0.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/bootstrap.min.js' %}" ></script>
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <form action="{% url 'score:activate_user' %}" method="POST" style="padding-top: 50px;">
                    {% csrf_token %}
                    <div class="page-header">
                        <h1>Activate User</h1>
                    </div>
                    <table class="table table-condensed">
                        <tbody>
                            <tr>
                                <td>Name:</td>
                                <td>{{ new_user.first_name }}</td>
                            </tr>
                            <tr>
                                <td>Surname:</td>
                                <td>{{ new_user.last_name }}</td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td>{{ new_user.email }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <input type="hidden" name="email" value="{{ new_user.email }}"/>
                    <footer style="text-align: right;"><button class="btn btn-primary" type="submit">Activate</button></footer>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
<script type="text/javascript">
    $(document).ready(function() {
        $("input[type='text']").value('')
        $("input[type='email']").value('')
        $("input[type='password']").value('')
    });
</script>
</body>
</html>

info/templates/info/assignment.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Score Web Services</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'score/js/jquery-1.12.0.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/bootstrap.min.js' %}" ></script>
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <form action="{% url 'score:user_assignment' %}" method="POST" style="padding-top: 50px; padding-bottom: 50px;">
                    {% csrf_token %}
                    <input name="username" type="hidden" value="{{ new_user.username }}" />
                    <div class="page-header">
                        <h1>Web Services &nbsp;&nbsp;&nbsp;&nbsp;<small><span class="label label-info">Select at least 20 Web Services</span></small></h1>
                    </div>
                    <table class="table table-hover">
                        <tbody>
                            {% for api in apis %}
                            <tr>
                                <td width="15%" style="position: relative;">
                                    <span style="position: absolute; right: 50%; bottom: 60%;">
                                        <input type="checkbox" name="ws{{ api.id }}" style="width: 20px; height: 20px;"/>
                                    </span>
                                    <br>
                                    <span style="position: absolute; bottom: 0; padding-bottom: 15px;">
                                        <b>Assigned to:&nbsp;</b>&nbsp;{{ api.num_scores }}
                                    </span>
                                </td>
                                <td>
                                    <a class="list-group-item" style="border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top-left-radius: 0px; border-top-right-radius: 0px; border: 0px solid #ddd; border-left: 1px solid #ddd;">
                                        <h4 class="list-group-item-heading">{{ api.name }}</h4>
                                        <p class="list-group-item-text">{{ api.description|slice:":300" }}</p>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <footer style="text-align: right;"><button class="btn btn-lg btn-primary" type="submit">Assign <span id="counter" class="badge">0</span></button></footer>
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
    <br>
    <footer style="text-align: center;"> <a href="http://www.lirmm.fr/~zela/">@jzelar</a> | <a href="http://www.lirmm.fr">LIRMM</a> | <a href="http://www.umontpellier.fr">Université de Montpellier</a></footer>
    <br>
<script type="text/javascript">
    $(document).ready(function() {
        counter = 0
        $("input[type='checkbox']").each(function(index) {
            if ($(this)[0].checked){
                counter = counter + 1;
                $("#counter").html(counter)
            }
        });

        $("input[type='checkbox']").on('click', function(){
            console.log($(this)[0].checked)
            if ($(this)[0].checked) {
                val = parseInt($("#counter").text())
                $("#counter").html(val + 1)
                console.log(val+1)
            } else {
                val = parseInt($("#counter").text())
                $("#counter").html(val - 1)
                console.log(val-1)
            }
        });
    });
    $(document).on('click', 'form button[type=submit]', function(e) {
        var isValid = false;
        counter = 0;
        $("input[type='checkbox']").each(function(index) {
            if ($(this)[0].checked){
                counter = counter + 1;
            }
        });
        console.log(counter)
        if (counter == 20) {
            isValid = true;
        }

        if(!isValid) {
          e.preventDefault();
          alert("Select at least 20 Web Services")
        }
    });
</script>
</body>
</html>

info/templates/info/confirmation.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Score Web Services</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'score/js/jquery-1.12.0.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/bootstrap.min.js' %}" ></script>
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% if type == 'signup' %}
                <div class="page-header">
                    <h2>Congratulations!!!</h2>
                </div>
                <p>
                    Your registration was done with success!<br>
                    Please, wait while your account is validated our team.<br>
                    Thank you.
                </p>
                {% elif type == 'activation' %}
                <div class="page-header">
                    <h2>Confirmation</h2>
                </div>
                <p>
                    User <b>{{ new_user.email }}</b> was activate successfully.
                </p>
                {% else %}
                <div class="page-header">
                    <h2>Error 404</h2>
                </div>
                {% endif %}
            </div>
            <div class="col-md-2"></div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <nav>
                    <ul class="pager">
                        <li class="next"><a href="/score_site/score">Return <span aria-hidden="true">&rarr;</span></a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</body>
</html>

info/templates/info/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'score/js/jquery-1.12.0.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/bootstrap.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/jquery.sticky.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/script.js' %}" ></script>
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/style.css' %}" />
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Score Web Services</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li style="padding-right: 40px;"><p class="navbar-text navbar-right">Signed in as <b>{{ user.username }}</b></p></li>
            <li class="active"><a href="/score_site/info/logout">Logout</a></li>
        </ul>
    </div>
</nav>
<div class="container-fluid">
{% block content %}{% endblock %}
</div>
<footer> <a href="http://www.lirmm.fr/~zela/">@jzelar</a> | <a href="http://www.lirmm.fr">LIRMM</a> | <a href="http://www.umontpellier.fr">Université de Montpellier</a></footer>
<br>
</body>
</html>

info/templates/info/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Rate Web Services</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'score/js/jquery-1.12.0.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/bootstrap.min.js' %}" ></script>
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/login.css' %}" />
</head>
<body>
    <div class="container">
        <form class="form-signin" action="{% url 'info:login' %}" method="POST">
            <h2 class="form-signin-heading">Info Web Service</h2>
            <h4 class="form-signin-heading">Please sign in</h4>
            {% csrf_token %}
            {% if login_error %}
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                {{login_error}}
            </div>
            {% endif %}
            {% if next %}
            <input type="hidden" name="next" value="{{ next }}"/>
            {% endif %}
            <label for="username" class="sr-only">Username</label>
            <input id="username" name="username" class="form-control input" placeholder="Username" required="" autofocus="" type="text">
            <label for="password" class="sr-only">Password</label>
            <input id="password" name="password" class="form-control input" placeholder="Password" required="" type="password">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <br>
            <!--footer style="text-align: center;"><a href="/score_site/rate/signup">Sign Up</a><footer-->
        </form>
    </div>
</body>
</html>

info/templates/info/main.html
{% extends "info/layout.html" %}

{% block title %}Web Services{% endblock %}

{% block content %}
    <style>
        #sticky {
            padding: 0.5ex;
            width: 600px;
            background-color: #333;
            color: #fff;
            font-size: 2em;
            border-radius: 0.5ex;
        }
    </style>
    <div class="jumbotron" style="background-color: #d9edf7; padding-bottom: 10px; padding-top: 10px;">
        {% if user.first_name|length == 0 %}
        <!--h1>Hello, {{ user.username }}!</h1-->
        <h1>Hello!</h1>
        {% else %}
        <!--h1>Hello, {{ user.first_name }}!</h1-->
        <h1>Hello!</h1>
        {% endif %}
        <p style="font-size: 18px;">We need your help!<br>Below you have a list of Web Service, you need to score each one
            according the showed extra information, described below, use your own criteria to score each Web service.<br>
            <br>Thank you so much for your time. :)<br>
            <br><b>Articles:</b> number of articles related to the Web services.
            <br><b>Followers:</b> number of followers which has the Web services.
            <br><b>Developers:</b> number of developers which use the Web services.
            <br><b>Mashups:</b> number of developed mashups using the Web services.
            <br><br>Referential numbers are also showed to get an overview about the minimal and maximal number of each
            information as well as the average and standard deviation.
        </p>
    </div>
    <br>
    <div id="references" class="alert alert-info text-center" role="alert">
        <div class="row">
            <div class="col-md-1" style="font-size: 20px;"></div>
            <div class="col-md-2" style="font-size: 20px;"><strong>References:</strong></div>
            {% for info in infos %}
            <div class="col-md-2" style="padding-left: 0px; padding-right: 0px;">
                Min/Max {{ info.name }}: <b style="font-size: 20px;">{{ info.min }}/{{ info.max }}</b><br>
                Average: <b style="font-size: 20px;">{{ info.mean }}</b><br>
                St Dev: <b style="font-size: 20px;">{{ info.stdev }}</b><br>
            </div>
            {% endfor %}
            <div class="col-md-1" style="font-size: 20px;"></div>
        </div>
    </div>
    <!--<div class="alert alert-info" role="alert">
        Please below, you have a list of Web Service, we need to go into each Web Service and score the comments which are inside.
        The score is according how positive or negative is for you.
    </div>-->
    <div class="page-header">
        <h1>Web Services</h1>
    </div>
    <div class="list-group" style="margin-left: 100px; margin-right: 100px">
        {% for api in apis %}
        <a class="list-group-item" style="position: inherit;">
            {% if api.scored == 1 %}
            <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true" style="color: #3c763d;"></span>
            {% endif %}
            <h4 class="list-group-item-heading">{{ api.name }}</h4>
            <p class="list-group-item-text">{{ api.description }}</p>
            <br>
            <p> <b>Articles</b>: <span class="badge">{{ api.articles }}</span> &nbsp;&nbsp;&nbsp; <b>Followers</b>: <span class="badge">{{ api.followers }}</span> &nbsp;&nbsp;&nbsp; <b>Developers</b>: <span class="badge">{{ api.developers }}</span> &nbsp;&nbsp;&nbsp; <b>Mashups</b>: <span class="badge">{{ api.mashups }}</span></p>
        </a>
        <nav id="{{ api.id }}">
            <span style="float: left; margin-top: 8px;"><b>Set a score:</b></span>&nbsp;&nbsp;
            <ul class="pagination pagination-sm" style="margin-top: 5px;">
                <li {% if api.info_score == 0 %} class="active" {% endif %} ><a href="#" style="position: inherit;">0</a></li>
                <li {% if api.info_score == 1 %} class="active" {% endif %} ><a href="#" style="position: inherit;">1</a></li>
                <li {% if api.info_score == 2 %} class="active" {% endif %} ><a href="#" style="position: inherit;">2</a></li>
                <li {% if api.info_score == 3 %} class="active" {% endif %} ><a href="#" style="position: inherit;">3</a></li>
                <li {% if api.info_score == 4 %} class="active" {% endif %} ><a href="#" style="position: inherit;">4</a></li>
                <li {% if api.info_score == 5 %} class="active" {% endif %} ><a href="#" style="position: inherit;">5</a></li>
            </ul>
        </nav>
        <br>
        {% endfor %}
    </div>
    <script type="text/javascript">
    $(document).ready(function() {
        $("#references").sticky({topSpacing:50});

        $('nav > ul').on('click', 'li > a', function(event){
            event.preventDefault();
            element = $(this);
            ws_id = element.parents("nav").attr('id');
            score = element.text();
            $('#wsalert').hide();
            $.ajax({
                url: "/score_site/info/webservice/infoscore",
                type: "post",
                cache: false,
                data: {'score':score, 'ws_id':ws_id},
                success: function(response) {
                    if (response['status'] == '200') {
                        $("#"+ws_id+">ul>li").each(function(){
                            $(this).removeClass('active')
                        });

                        element.parent().addClass('active');
                        //element.parents("blockquote").find('textarea').show();
                    }
                }
            });
        });
    });
    </script>
{% endblock %}

info/templates/info/signup.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Score Web Services</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'score/js/jquery-1.12.0.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'score/js/bootstrap.min.js' %}" ></script>
    <link rel="stylesheet" type="text/css" href="{% static 'score/css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <form action="{% url 'score:signup' %}" method="POST" style="padding-top: 50px;">
                    {% csrf_token %}
                    <div class="page-header">
                        <h1>Registration</h1>
                    </div>
                    {% if signup_error %}
                    <div class="alert alert-danger" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        {{signup_error}}
                    </div>
                    {% endif %}
                    <!--div class="form-group">
                        <label for="first_name">Name</label>
                        <input name="first_name" type="text" class="form-control" id="first_name" placeholder="Name" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="last_name">Surname</label>
                        <input name="last_name" type="text" class="form-control" id="last_name" placeholder="Surname" autocomplete="off">
                    </div-->
                    <div class="form-group">
                        <label for="email">Username*</label>
                        <input name="email" type="text" class="form-control" id="email" placeholder="Username" autocomplete="off" maxlength="30" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password*</label>
                        <input name="password" type="password" class="form-control" id="password" placeholder="Password" required>
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
<script type="text/javascript">
    $(document).ready(function() {
        $("input[type='text']").value('')
        $("input[type='email']").value('')
        $("input[type='password']").value('')
    });
</script>
</body>
</html>